export const MOCK_MOVIES = [
  {
    id: "1",
    title: "Interstellar",
    original_title: "Interstellar",
    overview: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento por garantizar la supervivencia de la humanidad.",
    release_year: 2014,
    duration: 169,
    language: "English",
    classification: "+13",
    director: "Christopher Nolan",
    cast_members: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    country: "USA",
    poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    vimeus_video_id: "example_video_id",
    is_featured: true,
    categories: ["Ciencia Ficción", "Drama", "Aventura"]
  },
  {
    id: "2",
    title: "El Caballero de la Noche",
    original_title: "The Dark Knight",
    overview: "Cuando la amenaza conocida como el Joker emerge de su pasado misterioso, causa estragos y caos en las personas de Gotham.",
    release_year: 2008,
    duration: 152,
    language: "English",
    classification: "+16",
    director: "Christopher Nolan",
    cast_members: "Christian Bale, Heath Ledger, Aaron Eckhart",
    country: "USA",
    poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    vimeus_video_id: "example_video_id_2",
    is_featured: false,
    categories: ["Acción", "Crimen", "Drama"]
  },
  {
    id: "3",
    title: "Inception",
    original_title: "Inception",
    overview: "Un ladrón que roba secretos corporativos mediante el uso de tecnología de compartir sueños, tiene la tarea inversa de plantar una idea en la mente de un CEO.",
    release_year: 2010,
    duration: 148,
    language: "English",
    classification: "+13",
    director: "Christopher Nolan",
    cast_members: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    country: "USA",
    poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/original/8ZTVqvKdQ8emSGUOM96WAiegZSR.jpg",
    vimeus_video_id: "example_video_id_3",
    is_featured: false,
    categories: ["Ciencia Ficción", "Acción"]
  },
  {
    id: "4",
    title: "Avengers: Endgame",
    original_title: "Avengers: Endgame",
    overview: "Después de los eventos devastadores de Avengers: Infinity War, el universo está en ruinas. Con la ayuda de los aliados restantes, los Vengadores se reúnen una vez más.",
    release_year: 2019,
    duration: 181,
    language: "English",
    classification: "+13",
    director: "Anthony Russo, Joe Russo",
    cast_members: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    country: "USA",
    poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    vimeus_video_id: "example_video_id_4",
    is_featured: false,
    categories: ["Acción", "Ciencia Ficción", "Aventura"]
  },
  {
    id: "5",
    title: "Joker",
    original_title: "Joker",
    overview: "En Gotham, Arthur Fleck, un comediante con problemas de salud mental, es marginado y maltratado por la sociedad. Se adentra en una espiral de revolución y crimen sangriento.",
    release_year: 2019,
    duration: 122,
    language: "English",
    classification: "+18",
    director: "Todd Phillips",
    cast_members: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    country: "USA",
    poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmIyHQgOUmhiG8a.jpg",
    vimeus_video_id: "example_video_id_5",
    is_featured: false,
    categories: ["Crimen", "Drama", "Thriller"]
  },
  {
    id: "6",
    title: "Matrix",
    original_title: "The Matrix",
    overview: "Un programador informático descubre que la realidad es una simulación creada por máquinas, y se une a una rebelión para liberar a la humanidad.",
    release_year: 1999,
    duration: 136,
    language: "English",
    classification: "+16",
    director: "Lana Wachowski, Lilly Wachowski",
    cast_members: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    country: "USA",
    poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/original/ncEsesgOJDNrTUED89hYbA117wo.jpg",
    vimeus_video_id: "example_video_id_6",
    is_featured: false,
    categories: ["Acción", "Ciencia Ficción"]
  }
];

export const MOCK_CATEGORIES = [
  { id: "1", name: "Estrenos" },
  { id: "2", name: "Acción" },
  { id: "3", name: "Ciencia Ficción" },
  { id: "4", name: "Drama" },
];
